apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage

resources:
  - ingress.yaml
  - rbac.yaml
  - config.yaml
  - secret.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.0
    releaseName: homepage
    namespace: homepage
    valuesFile: values.yaml
