---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homeassistant
  namespace: home
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: home-assistant.png
    gethomepage.dev/name: Home Assistant
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=home-assistant"
    gethomepage.dev/group: Home Automation
    gethomepage.dev/description: "Open source home automation platform"
spec:
  parentRefs:
  - name: one-gateway-for-all
    namespace: envoy-gateway-system
    sectionName: https
  hostnames:
  - ha.lac-coloc.fr
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: home-assistant
      port: 8123
---
# HTTPRoute pour HTTP (redirection 301)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homeassistant-http-redirect
  namespace: home
spec:
  parentRefs:
  - name: one-gateway-for-all
    namespace: envoy-gateway-system
    sectionName: http
  hostnames:
  - ha.lac-coloc.fr
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
