apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home

resources:
  - ingress.yaml
  - pvc.yaml

helmCharts:
  - name: home-assistant
    repo: http://pajikos.github.io/home-assistant-helm-chart/
    version: 0.3.39
    releaseName: home-assistant
    namespace: home
    valuesFile: values.yaml
