apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab-runner

resources:
  - secret.yaml

helmCharts:
  - name: gitlab-runner
    repo: https://charts.gitlab.io
    version: 0.84.1
    releaseName: gitlab-runner
    namespace: gitlab-runner
    valuesFile: values.yaml
