---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway-api-crds.yaml
  - envoy-gateway.yaml
  - gateway-class.yaml
  - one-gateway-for-all.yaml
  - ipv6-listener-patch.yaml
  - manual/st1-age.yaml
