apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: medias

resources:
  - ./jellyfin
  - ./jellyseerr
  - ./jellystat
  - ./sonarr
  - ./radarr
  - ./lidarr
  - ./prowlarr
  - ./flaresolverr
