apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin

resources:
  - nfs-pv.yaml
  - ingress.yaml

helmCharts:
  - name: jellyfin
    repo: https://jellyfin.github.io/jellyfin-helm
    namespace: jellyfin
    releaseName: jellyfin
    valuesFile: values.yaml
    version: 2.5.0
