---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv
spec:
  capacity:
    storage: 30Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
  nfs:
    server: 10.243.2.11
    path: /mnt/data-hdd/medias
  mountOptions:
    - nfsvers=4
    - rw
    - noatime
    - timeo=300
    - nolock
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-pvc
  annotations:
    velero.io/exclude-from-backup: true
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 30Ti
