replicaCount: 1

image:
  repository: docker.io/jellyfin/jellyfin
  tag: 10.11.6
  pullPolicy: Always

podAnnotations:
  backup.velero.io/backup-volumes-excludes: media,media2

nodeSelector:
  beta.kubernetes.io/arch: amd64

serviceAccount:
  create: true
  automount: true

service:
  type: ClusterIP
  port: 8096
  portName: service

ingress:
  enabled: false

resources:
  limits:
    memory: 4096Mi
  requests:
    cpu: 100m
    memory: 128Mi

# -- Configure liveness probe for Jellyfin.
livenessProbe:
  initialDelaySeconds: 10
  tcpSocket:
    port: http

readinessProbe:
  initialDelaySeconds: 10
  tcpSocket:
    port: http

jellyfin:
  enableDLNA: false

persistence:
  config:
    enabled: true
    type: pvc
    existingClaim: jellyfin-config
  media:
    enabled: true
    type: pvc
    existingClaim: nfs-media-pvc

volumes:
  - name: media2
    persistentVolumeClaim:
      claimName: nfs-media-pvc-2

volumeMounts:
  - mountPath: /media2
    name: media2

# -- Configuration for metrics collection and monitoring
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 30s
    path: /metrics
    port: 8096
    scheme: http
