---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nodered-https-route
  namespace: home
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: node-red.png
    gethomepage.dev/name: Node-RED
    gethomepage.dev/group: Home Automation
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=node-red"
    gethomepage.dev/description: "Flow-based programming for IoT"
spec:
  parentRefs:
  - name: one-gateway-for-all
    namespace: envoy-gateway-system
    sectionName: https
  hostnames:
  - node-red.lafranque.net
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: node-red
      namespace: home
      port: 1880
---
# HTTPRoute pour HTTP (redirection 301)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: node-red-http-redirect
  namespace: home
spec:
  parentRefs:
  - name: one-gateway-for-all
    namespace: envoy-gateway-system
    sectionName: http
  hostnames:
  - node-red.lafranque.net
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: node-red
  namespace: home
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: nodered-https-route
  basicAuth:
    users:
      name: nodered
