apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: medias

resources:
  - ingress.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts/
    version: 4.6.0
    releaseName: sonarr
    namespace: medias
    valuesFile: values.yaml
